In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv')
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [3]:
df.shape

(9999, 9)

In [9]:
df.isnull()

      MOVIES   YEAR  GENRE  RATING  ONE-LINE  STARS  VOTES  RunTime  Gross
0      False  False  False   False     False  False  False    False   True
1      False  False  False   False     False  False  False    False   True
2      False  False  False   False     False  False  False    False   True
3      False  False  False   False     False  False  False    False   True
4      False  False  False    True     False  False   True     True   True
...      ...    ...    ...     ...       ...    ...    ...      ...    ...
9994   False  False  False    True     False  False   True     True   True
9995   False  False  False    True     False  False   True     True   True
9996   False  False  False    True     False  False   True     True   True
9997   False  False  False    True     False  False   True     True   True
9998   False  False  False    True     False  False   True     True   True

[9999 rows x 9 columns]

In [12]:
df['Gross'].fillna('N/A', inplace= True)

In [13]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,N/A
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,N/A
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,N/A
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,N/A
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,N/A
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,N/A
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,N/A
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,N/A
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,N/A
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,N/A

In [14]:
df.isnull()

      MOVIES   YEAR  GENRE  RATING  ONE-LINE  STARS  VOTES  RunTime  Gross
0      False  False  False   False     False  False  False    False  False
1      False  False  False   False     False  False  False    False  False
2      False  False  False   False     False  False  False    False  False
3      False  False  False   False     False  False  False    False  False
4      False  False  False    True     False  False   True     True  False
...      ...    ...    ...     ...       ...    ...    ...      ...    ...
9994   False  False  False    True     False  False   True     True  False
9995   False  False  False    True     False  False   True     True  False
9996   False  False  False    True     False  False   True     True  False
9997   False  False  False    True     False  False   True     True  False
9998   False  False  False    True     False  False   True     True  False

[9999 rows x 9 columns]

In [20]:
d = df.isnull().sum()
d /= 9999
d *= 100
d

MOVIES       0.000000
YEAR         6.440644
GENRE        0.800080
RATING      18.201820
ONE-LINE     0.000000
STARS        0.000000
VOTES       18.201820
RunTime     29.582958
Gross        0.000000
dtype: float64

In [21]:
df.dropna(inplace=True)

In [22]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,N/A
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,N/A
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,N/A
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,N/A
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,N/A
...,...,...,...,...,...,...,...,...,...
9959,Sexify,(2021– ),"\nComedy, Drama",6.8,"\nMonika's idea for gathering data is a hit, b...",\n Director:\nKalina Alabrudzinska\n| \n ...,108,38.0,N/A
9960,Sexify,(2021– ),"\nComedy, Drama",7.1,\nAfter facing their parents at Easter breakfa...,\n Director:\nKalina Alabrudzinska\n| \n ...,103,37.0,N/A
9961,Sexify,(2021– ),"\nComedy, Drama",6.9,\nAfter getting an anonymous tip about the cop...,\n Director:\nKalina Alabrudzinska\n| \n ...,96,40.0,N/A
9962,Sexify,(2021– ),"\nComedy, Drama",7.1,\nThe big pitch at the university tech competi...,\n Director:\nKalina Alabrudzinska\n| \n ...,100,47.0,N/A
9963,Castlevania,(2017–2021),"\nAnimation, Action, Adventure",8.2,\nLenore urges Hector to not test Camilla's pa...,\n Director:\nSam Deats\n| \n Stars:\nRi...,911,24.0,N/A

In [24]:
(6779 / 9999) * 100

67.7967796779678

In [25]:
df.duplicated()

0       False
1       False
2       False
3       False
5       False
        ...
9959    False
9960    False
9961    False
9962    False
9963    False
Length: 6779, dtype: bool

In [26]:
df.drop_duplicates(inplace= True)

In [27]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,N/A
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,N/A
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,N/A
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,N/A
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,N/A
...,...,...,...,...,...,...,...,...,...
9959,Sexify,(2021– ),"\nComedy, Drama",6.8,"\nMonika's idea for gathering data is a hit, b...",\n Director:\nKalina Alabrudzinska\n| \n ...,108,38.0,N/A
9960,Sexify,(2021– ),"\nComedy, Drama",7.1,\nAfter facing their parents at Easter breakfa...,\n Director:\nKalina Alabrudzinska\n| \n ...,103,37.0,N/A
9961,Sexify,(2021– ),"\nComedy, Drama",6.9,\nAfter getting an anonymous tip about the cop...,\n Director:\nKalina Alabrudzinska\n| \n ...,96,40.0,N/A
9962,Sexify,(2021– ),"\nComedy, Drama",7.1,\nThe big pitch at the university tech competi...,\n Director:\nKalina Alabrudzinska\n| \n ...,100,47.0,N/A
9963,Castlevania,(2017–2021),"\nAnimation, Action, Adventure",8.2,\nLenore urges Hector to not test Camilla's pa...,\n Director:\nSam Deats\n| \n Stars:\nRi...,911,24.0,N/A

In [30]:
df.to_csv('cleaned_movies.csv', index=False)